import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import test from "node:test"

const server = await readFile(new URL("../src/index.ts", import.meta.url), "utf8")
const goalServer = await readFile(new URL("../../orchestration-policy/src/index.ts", import.meta.url), "utf8")
const tui = await readFile(new URL("../src/tui.tsx", import.meta.url), "utf8")
const activeRow = await readFile(new URL("../src/active-subagent-row.ts", import.meta.url), "utf8")
const goalHandoff = await readFile(new URL("../src/goal-handoff-control.ts", import.meta.url), "utf8")
const goalSettings = await readFile(new URL("../src/goal-ui-settings.ts", import.meta.url), "utf8")
const rpc = await readFile(new URL("../src/rpc.ts", import.meta.url), "utf8")
const todoTui = await readFile(new URL("../../rig-todo/src/tui.tsx", import.meta.url), "utf8")
const fileManagerTui = await readFile(new URL("../../file-manager/src/tui.tsx", import.meta.url), "utf8")
const roleCatalog = JSON.parse(await readFile(new URL("../../../config/v2-plugin-roles.json", import.meta.url), "utf8")) as {
  plugins: Array<{ name: string; roles: Record<string, unknown> }>
}
const cliExample = JSON.parse(await readFile(new URL("../../../config/v2-cli.example.json", import.meta.url), "utf8")) as {
  plugins: Array<{ package: string }>
}

test("visible slash commands use the CLI dialog path, not a synthetic inbox body", () => {
  assert.doesNotMatch(server, /ctx\.command\.transform/)
  assert.doesNotMatch(server, /ctx\.session\.synthetic/)
  assert.match(server, /ctx\.rpc\.register\(RigTools/)
  assert.match(tui, /message = await run\(\)/)
  assert.match(tui, /The command failed\. Restart OpenCode if the server plugin is not loaded\./)
  assert.match(tui, /slash: \{ name: "tools", arguments: true \}/)
  assert.match(tui, /slash: \{ name: "goal", arguments: true \}/)
  assert.match(tui, /Use \/goal build to start a ready Plan explicitly/)
  assert.match(tui, /goalRpc\.command\(/)
  assert.match(tui, /context\.client\.session\.inbox\.cancel\(/)
  assert.match(tui, /append: "prompt\.footer\.status"/)
  assert.match(goalHandoff, /id: "opencode-rig\.goal-handoff"/)
  assert.match(goalServer, /ctx\.session\.wait\(/)
  assert.doesNotMatch(goalServer, /ctx\.session\.(?:active|inbox)\b/)
  assert.match(tui, /palette: true/)
  assert.match(goalHandoff, /event\.name !== "return" && event\.name !== "space"/)
  assert.match(goalHandoff, /event\.button !== 0/)
  assert.doesNotMatch(tui, /context\.data\.on\("session\.execution\.succeeded"/)
  assert.match(goalServer, /event\.type === "session\.execution\.succeeded"/)
  assert.match(tui, /context\.storage\.store\("goal-ui-settings"/)
  assert.match(tui, /showGoalSettingsPalette\(context/)
  assert.equal(tui.match(/id: "opencode-rig\.settings"/g)?.length, 1)
  assert.equal(tui.match(/title: "Open Rig workflow settings"/g)?.length, 1)
  assert.doesNotMatch(tui, /slash:\s*\{\s*name:\s*"(?:settings|goal-handoff)"/)
  assert.match(goalSettings, /footerGoal: true,\s+sidebarGoal: true,\s+hoverPreview: true/)
  assert.match(goalSettings, /value: "handoff"/)
  assert.match(goalSettings, /toggleHandoff\(sessionID\)/)
  assert.match(tui, /typeof sessionID === "string"/)
  assert.match(goalHandoff, /onMouseOver: \(\) => setHovered\(true\)/)
  assert.match(goalHandoff, /onMouseOut: \(\) => setHovered\(false\)/)
  assert.match(goalHandoff, /focused_renderable/)
  assert.match(tui, /never starts a model turn/)
  assert.doesNotMatch(server, /name:\s*["']settings["']/)
  assert.doesNotMatch(server, /settings.*(?:RPC|tool)|(?:RPC|tool).*settings/i)
  assert.match(tui, /slash: \{ name: "session-context", arguments: true \}/)
  assert.match(tui, /slash: \{ name: "subagents" \}/)
  assert.match(tui, /append: "session\.panel"/)
  assert.match(tui, /const requests = new AbortController\(\)/)
  assert.match(tui, /context\.client\.session\.active\(requestOptions\)/)
  assert.match(tui, /subagentStatus\(child, active\[child\.id\]\?\.type === "running"\)/)
  assert.match(tui, /context\.data\.on\("session\.status", \(\) => \{\s+void refresh\(\)/)
  assert.match(tui, /setInterval\(\(\) => void refresh\(\), 1_000\)/)
  assert.match(tui, /clearInterval\(timer\)/)
  assert.match(tui, /requests\.abort\(\)/)
  assert.match(tui, /const opened = context\.ui\.panel\.open\(SUBAGENTS_PANEL_NAME/)
  assert.match(tui, /This view requires an active session\./)
  assert.match(tui, /formatSubagentRow\(row/)
  assert.match(tui, /useKeyboard\(\(key\) => \{/)
  assert.match(tui, /if \(!props\.panel\.focused\) return/)
  assert.match(tui, /if \(key\.name === "escape"\) \{/)
  assert.match(tui, /if \(key\.name === "h"\) \{/)
  assert.match(tui, /key\.stopPropagation\(\)/)
  assert.match(tui, /slash: \{ name: "subagents-history", arguments: true \}/)
  assert.match(tui, /recordSubagentObservations\(subagentHistoryRoot\(\), next, new Date\(\)\.toISOString\(\)\)/)
  assert.match(tui, /querySubagentHistoryEvents\(subagentHistoryRoot\(\)/)
  assert.match(tui, /historyCursors\[page \+ 1\] = result\.nextBeforeSeq/)
  assert.match(tui, /<SubagentsHistory/)
  assert.match(tui, /export function ActiveSubagentsSidebar/)
  assert.match(activeRow, /props\.collapsed \? "\+" : "-"\} Active Subagents/)
  assert.match(activeRow, /` \$\{props\.count\}`/)
  assert.match(activeRow, /focusable: true/)
  assert.match(activeRow, /id: "opencode-rig\.active-subagents\.heading"/)
  assert.match(activeRow, /width: "100%"/)
  assert.match(activeRow, /onMouseDown: activate/)
  assert.match(activeRow, /event\.name !== "return" && event\.name !== "space"/)
  assert.match(activeRow, /event\.button !== 0/)
  assert.match(tui, /const \[collapsed, setCollapsed\] = createSignal\(false\)/)
  assert.match(tui, /<Show when=\{!collapsed\(\)\}>/)
  assert.match(tui, /queueMicrotask\(\(\) => headingRef\?\.focus\(\)\)/)
  assert.match(tui, /<ActiveSubagentsHeading/)
  assert.match(tui, /attributes=\{TextAttributes\.DIM\}/)
  assert.match(tui, /<ActiveSubagentRow/)
  assert.match(activeRow, /activeSubagentRowStyle\(props\.theme, props\.focused\)/)
  assert.match(activeRow, /Agent · \$\{props\.row\.agent\}/)
  assert.match(activeRow, /paddingLeft: 2/)
  assert.match(activeRow, /get style\(\) \{ return \{ fg: style\(\)\.markerColor \} \}/)
  assert.match(activeRow, /get style\(\) \{ return \{ fg: style\(\)\.agentColor \} \}/)
  assert.match(activeRow, /jsx\("b", \{ children: ` · Agent · \$\{props\.row\.agent\}` \}\)/)
  assert.match(activeRow, /attributes: TextAttributes\.DIM/)
  assert.match(activeRow, /get backgroundColor\(\) \{ return style\(\)\.backgroundColor \}/)
  assert.doesNotMatch(activeRow, /backgroundColor=\{[^}]*undefined/)
  assert.doesNotMatch(activeRow, /backgroundColor:\s*undefined/)
  assert.doesNotMatch(activeRow, /(?:#000(?:000)?|0x000000|\bblack\b|#fff(?:fff)?|0xffffff|\bwhite\b)/i)
  assert.equal(activeRow.match(/wrapMode: "word"/g)?.length, 4)
  assert.doesNotMatch(activeRow, /truncate: true/)
  assert.doesNotMatch(tui, /(?:#000(?:000)?|0x000000|\bblack\b)/i)
  assert.match(tui, /context\.ui\.router\.navigate\(\{ type: "session", sessionID \}\)/)
  assert.match(tui, /Click\/Enter opens · ↑\/↓ moves/)
  assert.match(tui, /const rpcOptions = \{ location: context\.location \}/)
  assert.match(tui, /rpc\.sessionContext\([^\n]+, rpcOptions\)/)
  assert.match(tui, /rpc\.managedScreens\(\{\}, rpcOptions\)/)
  assert.match(tui, /rpc\.events\.on\("managedScreensChanged"/)
  assert.match(server, /rpc\.events\.emit\("managedScreensChanged", \{\}\)/)
  assert.match(tui, /<ManagedScreensSidebar/)
  assert.match(rpc, /RigToolsManagedScreen = \{ name: string; state: string \}/)
  assert.doesNotMatch(rpc, /\bpid\b/iu)
})

test("sidebar preserves native MCP content while adding Explorer, Todo, and active subagents", () => {
  assert.match(fileManagerTui, /before: "sidebar\.content"/)
  assert.match(tui, /after: "sidebar\.content"/)
  assert.doesNotMatch(tui, /replace: "sidebar\.content"/)
  assert.match(todoTui, /after: "sidebar\.content"/)
  assert.doesNotMatch(fileManagerTui, /append: "sidebar\.content"/)
  assert.doesNotMatch(todoTui, /append: "sidebar\.content"/)
  assert.doesNotMatch(tui, /function McpSidebar|mcpStatusText|mcpStatusCounts/)
  assert.match(tui, /<ActiveSubagentsSidebar sessionID=\{sessionID\} \/>/)
  assert.match(tui, /<ManagedScreensSidebar/)
  assert.doesNotMatch(tui, /session\.composer\.top/)
})

test("queries bounded direct child sessions across worktree directories", () => {
  const query = tui.match(/context\.client\.session\.list\(\{\s*([\s\S]*?)\s*\}, requestOptions\)/u)
  assert.ok(query)
  assert.match(query[1]!, /parentID:\s*parent\.id/u)
  assert.match(query[1]!, /project:\s*parent\.projectID/u)
  assert.match(query[1]!, /limit:\s*MAX_SUBAGENT_ROWS/u)
  assert.doesNotMatch(query[1]!, /\bdirectory\s*:/u)
})

test("canonical role catalog and CLI example register both rig-tools roles", () => {
  const roles = roleCatalog.plugins.find((plugin) => plugin.name === "rig-tools")?.roles
  assert.deepEqual(Object.keys(roles ?? {}).sort(), ["cli", "server"])
  assert.equal(cliExample.plugins.some((plugin) => plugin.package.endsWith("/plugins-v2/rig-tools")), true)
})
